// src/utils/countries.js
// Complete world countries with currency, locale, and flag data

export const COUNTRIES = [
  { code: 'AF', name: 'Afghanistan',           currency: 'AFN', currencyName: 'Afghan Afghani',        symbol: '؋',   locale: 'fa-AF' },
  { code: 'AL', name: 'Albania',               currency: 'ALL', currencyName: 'Albanian Lek',           symbol: 'L',   locale: 'sq-AL' },
  { code: 'DZ', name: 'Algeria',               currency: 'DZD', currencyName: 'Algerian Dinar',         symbol: 'د.ج', locale: 'ar-DZ' },
  { code: 'AO', name: 'Angola',                currency: 'AOA', currencyName: 'Angolan Kwanza',         symbol: 'Kz',  locale: 'pt-AO' },
  { code: 'AR', name: 'Argentina',             currency: 'ARS', currencyName: 'Argentine Peso',         symbol: '$',   locale: 'es-AR' },
  { code: 'AM', name: 'Armenia',               currency: 'AMD', currencyName: 'Armenian Dram',          symbol: '֏',   locale: 'hy-AM' },
  { code: 'AU', name: 'Australia',             currency: 'AUD', currencyName: 'Australian Dollar',      symbol: 'A$',  locale: 'en-AU' },
  { code: 'AT', name: 'Austria',               currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'de-AT' },
  { code: 'AZ', name: 'Azerbaijan',            currency: 'AZN', currencyName: 'Azerbaijani Manat',      symbol: '₼',   locale: 'az-AZ' },
  { code: 'BH', name: 'Bahrain',               currency: 'BHD', currencyName: 'Bahraini Dinar',         symbol: '.د.ب',locale: 'ar-BH' },
  { code: 'BD', name: 'Bangladesh',            currency: 'BDT', currencyName: 'Bangladeshi Taka',       symbol: '৳',   locale: 'bn-BD' },
  { code: 'BY', name: 'Belarus',               currency: 'BYN', currencyName: 'Belarusian Ruble',       symbol: 'Br',  locale: 'be-BY' },
  { code: 'BE', name: 'Belgium',               currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'nl-BE' },
  { code: 'BJ', name: 'Benin',                 currency: 'XOF', currencyName: 'West African CFA Franc', symbol: 'Fr',  locale: 'fr-BJ' },
  { code: 'BO', name: 'Bolivia',               currency: 'BOB', currencyName: 'Bolivian Boliviano',     symbol: 'Bs.', locale: 'es-BO' },
  { code: 'BA', name: 'Bosnia and Herzegovina',currency: 'BAM', currencyName: 'Bosnian Mark',           symbol: 'KM',  locale: 'bs-BA' },
  { code: 'BW', name: 'Botswana',              currency: 'BWP', currencyName: 'Botswana Pula',          symbol: 'P',   locale: 'en-BW' },
  { code: 'BR', name: 'Brazil',                currency: 'BRL', currencyName: 'Brazilian Real',         symbol: 'R$',  locale: 'pt-BR' },
  { code: 'BN', name: 'Brunei',                currency: 'BND', currencyName: 'Brunei Dollar',          symbol: 'B$',  locale: 'ms-BN' },
  { code: 'BG', name: 'Bulgaria',              currency: 'BGN', currencyName: 'Bulgarian Lev',          symbol: 'лв',  locale: 'bg-BG' },
  { code: 'BF', name: 'Burkina Faso',          currency: 'XOF', currencyName: 'West African CFA Franc', symbol: 'Fr',  locale: 'fr-BF' },
  { code: 'BI', name: 'Burundi',               currency: 'BIF', currencyName: 'Burundian Franc',        symbol: 'Fr',  locale: 'fr-BI' },
  { code: 'CV', name: 'Cabo Verde',            currency: 'CVE', currencyName: 'Cape Verdean Escudo',    symbol: '$',   locale: 'pt-CV' },
  { code: 'KH', name: 'Cambodia',              currency: 'KHR', currencyName: 'Cambodian Riel',         symbol: '៛',   locale: 'km-KH' },
  { code: 'CM', name: 'Cameroon',              currency: 'XAF', currencyName: 'Central African CFA',    symbol: 'Fr',  locale: 'fr-CM' },
  { code: 'CA', name: 'Canada',                currency: 'CAD', currencyName: 'Canadian Dollar',        symbol: 'C$',  locale: 'en-CA' },
  { code: 'CF', name: 'Central African Rep.',  currency: 'XAF', currencyName: 'Central African CFA',    symbol: 'Fr',  locale: 'fr-CF' },
  { code: 'TD', name: 'Chad',                  currency: 'XAF', currencyName: 'Central African CFA',    symbol: 'Fr',  locale: 'fr-TD' },
  { code: 'CL', name: 'Chile',                 currency: 'CLP', currencyName: 'Chilean Peso',           symbol: '$',   locale: 'es-CL' },
  { code: 'CN', name: 'China',                 currency: 'CNY', currencyName: 'Chinese Yuan',           symbol: '¥',   locale: 'zh-CN' },
  { code: 'CO', name: 'Colombia',              currency: 'COP', currencyName: 'Colombian Peso',         symbol: '$',   locale: 'es-CO' },
  { code: 'CD', name: 'Congo (DRC)',            currency: 'CDF', currencyName: 'Congolese Franc',        symbol: 'Fr',  locale: 'fr-CD' },
  { code: 'CR', name: 'Costa Rica',            currency: 'CRC', currencyName: 'Costa Rican Colón',      symbol: '₡',   locale: 'es-CR' },
  { code: 'CI', name: "Côte d'Ivoire",         currency: 'XOF', currencyName: 'West African CFA Franc', symbol: 'Fr',  locale: 'fr-CI' },
  { code: 'HR', name: 'Croatia',               currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'hr-HR' },
  { code: 'CU', name: 'Cuba',                  currency: 'CUP', currencyName: 'Cuban Peso',             symbol: '$',   locale: 'es-CU' },
  { code: 'CY', name: 'Cyprus',                currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'el-CY' },
  { code: 'CZ', name: 'Czechia',               currency: 'CZK', currencyName: 'Czech Koruna',           symbol: 'Kč',  locale: 'cs-CZ' },
  { code: 'DK', name: 'Denmark',               currency: 'DKK', currencyName: 'Danish Krone',           symbol: 'kr',  locale: 'da-DK' },
  { code: 'DJ', name: 'Djibouti',              currency: 'DJF', currencyName: 'Djiboutian Franc',       symbol: 'Fr',  locale: 'fr-DJ' },
  { code: 'DO', name: 'Dominican Republic',    currency: 'DOP', currencyName: 'Dominican Peso',         symbol: 'RD$', locale: 'es-DO' },
  { code: 'EC', name: 'Ecuador',               currency: 'USD', currencyName: 'US Dollar',              symbol: '$',   locale: 'es-EC' },
  { code: 'EG', name: 'Egypt',                 currency: 'EGP', currencyName: 'Egyptian Pound',         symbol: 'E£',  locale: 'ar-EG' },
  { code: 'SV', name: 'El Salvador',           currency: 'USD', currencyName: 'US Dollar',              symbol: '$',   locale: 'es-SV' },
  { code: 'GQ', name: 'Equatorial Guinea',     currency: 'XAF', currencyName: 'Central African CFA',    symbol: 'Fr',  locale: 'es-GQ' },
  { code: 'ER', name: 'Eritrea',               currency: 'ERN', currencyName: 'Eritrean Nakfa',         symbol: 'Nfk', locale: 'ti-ER' },
  { code: 'EE', name: 'Estonia',               currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'et-EE' },
  { code: 'SZ', name: 'Eswatini',              currency: 'SZL', currencyName: 'Swazi Lilangeni',        symbol: 'L',   locale: 'en-SZ' },
  { code: 'ET', name: 'Ethiopia',              currency: 'ETB', currencyName: 'Ethiopian Birr',         symbol: 'Br',  locale: 'am-ET' },
  { code: 'FJ', name: 'Fiji',                  currency: 'FJD', currencyName: 'Fijian Dollar',          symbol: 'FJ$', locale: 'en-FJ' },
  { code: 'FI', name: 'Finland',               currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'fi-FI' },
  { code: 'FR', name: 'France',                currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'fr-FR' },
  { code: 'GA', name: 'Gabon',                 currency: 'XAF', currencyName: 'Central African CFA',    symbol: 'Fr',  locale: 'fr-GA' },
  { code: 'GM', name: 'Gambia',                currency: 'GMD', currencyName: 'Gambian Dalasi',         symbol: 'D',   locale: 'en-GM' },
  { code: 'GE', name: 'Georgia',               currency: 'GEL', currencyName: 'Georgian Lari',         symbol: '₾',   locale: 'ka-GE' },
  { code: 'DE', name: 'Germany',               currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'de-DE' },
  { code: 'GH', name: 'Ghana',                 currency: 'GHS', currencyName: 'Ghanaian Cedi',          symbol: '₵',   locale: 'en-GH' },
  { code: 'GR', name: 'Greece',                currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'el-GR' },
  { code: 'GT', name: 'Guatemala',             currency: 'GTQ', currencyName: 'Guatemalan Quetzal',     symbol: 'Q',   locale: 'es-GT' },
  { code: 'GN', name: 'Guinea',                currency: 'GNF', currencyName: 'Guinean Franc',          symbol: 'Fr',  locale: 'fr-GN' },
  { code: 'GW', name: 'Guinea-Bissau',         currency: 'XOF', currencyName: 'West African CFA Franc', symbol: 'Fr',  locale: 'pt-GW' },
  { code: 'GY', name: 'Guyana',                currency: 'GYD', currencyName: 'Guyanese Dollar',        symbol: 'G$',  locale: 'en-GY' },
  { code: 'HT', name: 'Haiti',                 currency: 'HTG', currencyName: 'Haitian Gourde',         symbol: 'G',   locale: 'fr-HT' },
  { code: 'HN', name: 'Honduras',              currency: 'HNL', currencyName: 'Honduran Lempira',       symbol: 'L',   locale: 'es-HN' },
  { code: 'HK', name: 'Hong Kong',             currency: 'HKD', currencyName: 'Hong Kong Dollar',       symbol: 'HK$', locale: 'zh-HK' },
  { code: 'HU', name: 'Hungary',               currency: 'HUF', currencyName: 'Hungarian Forint',       symbol: 'Ft',  locale: 'hu-HU' },
  { code: 'IS', name: 'Iceland',               currency: 'ISK', currencyName: 'Icelandic Króna',        symbol: 'kr',  locale: 'is-IS' },
  { code: 'IN', name: 'India',                 currency: 'INR', currencyName: 'Indian Rupee',           symbol: '₹',   locale: 'en-IN' },
  { code: 'ID', name: 'Indonesia',             currency: 'IDR', currencyName: 'Indonesian Rupiah',      symbol: 'Rp',  locale: 'id-ID' },
  { code: 'IR', name: 'Iran',                  currency: 'IRR', currencyName: 'Iranian Rial',           symbol: '﷼',   locale: 'fa-IR' },
  { code: 'IQ', name: 'Iraq',                  currency: 'IQD', currencyName: 'Iraqi Dinar',            symbol: 'ع.د', locale: 'ar-IQ' },
  { code: 'IE', name: 'Ireland',               currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'en-IE' },
  { code: 'IL', name: 'Israel',                currency: 'ILS', currencyName: 'Israeli New Shekel',     symbol: '₪',   locale: 'he-IL' },
  { code: 'IT', name: 'Italy',                 currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'it-IT' },
  { code: 'JM', name: 'Jamaica',               currency: 'JMD', currencyName: 'Jamaican Dollar',        symbol: 'J$',  locale: 'en-JM' },
  { code: 'JP', name: 'Japan',                 currency: 'JPY', currencyName: 'Japanese Yen',           symbol: '¥',   locale: 'ja-JP' },
  { code: 'JO', name: 'Jordan',                currency: 'JOD', currencyName: 'Jordanian Dinar',        symbol: 'JD',  locale: 'ar-JO' },
  { code: 'KZ', name: 'Kazakhstan',            currency: 'KZT', currencyName: 'Kazakhstani Tenge',      symbol: '₸',   locale: 'kk-KZ' },
  { code: 'KE', name: 'Kenya',                 currency: 'KES', currencyName: 'Kenyan Shilling',        symbol: 'Ksh', locale: 'en-KE' },
  { code: 'KW', name: 'Kuwait',                currency: 'KWD', currencyName: 'Kuwaiti Dinar',          symbol: 'KD',  locale: 'ar-KW' },
  { code: 'KG', name: 'Kyrgyzstan',            currency: 'KGS', currencyName: 'Kyrgystani Som',         symbol: 'с',   locale: 'ky-KG' },
  { code: 'LA', name: 'Laos',                  currency: 'LAK', currencyName: 'Lao Kip',               symbol: '₭',   locale: 'lo-LA' },
  { code: 'LV', name: 'Latvia',                currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'lv-LV' },
  { code: 'LB', name: 'Lebanon',               currency: 'LBP', currencyName: 'Lebanese Pound',         symbol: 'L£',  locale: 'ar-LB' },
  { code: 'LS', name: 'Lesotho',               currency: 'LSL', currencyName: 'Lesotho Loti',           symbol: 'L',   locale: 'en-LS' },
  { code: 'LR', name: 'Liberia',               currency: 'LRD', currencyName: 'Liberian Dollar',        symbol: 'L$',  locale: 'en-LR' },
  { code: 'LY', name: 'Libya',                 currency: 'LYD', currencyName: 'Libyan Dinar',           symbol: 'LD',  locale: 'ar-LY' },
  { code: 'LI', name: 'Liechtenstein',         currency: 'CHF', currencyName: 'Swiss Franc',            symbol: 'Fr',  locale: 'de-LI' },
  { code: 'LT', name: 'Lithuania',             currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'lt-LT' },
  { code: 'LU', name: 'Luxembourg',            currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'fr-LU' },
  { code: 'MO', name: 'Macao',                 currency: 'MOP', currencyName: 'Macanese Pataca',        symbol: 'P',   locale: 'zh-MO' },
  { code: 'MG', name: 'Madagascar',            currency: 'MGA', currencyName: 'Malagasy Ariary',        symbol: 'Ar',  locale: 'mg-MG' },
  { code: 'MW', name: 'Malawi',                currency: 'MWK', currencyName: 'Malawian Kwacha',        symbol: 'MK',  locale: 'en-MW' },
  { code: 'MY', name: 'Malaysia',              currency: 'MYR', currencyName: 'Malaysian Ringgit',      symbol: 'RM',  locale: 'ms-MY' },
  { code: 'MV', name: 'Maldives',              currency: 'MVR', currencyName: 'Maldivian Rufiyaa',      symbol: 'Rf',  locale: 'dv-MV' },
  { code: 'ML', name: 'Mali',                  currency: 'XOF', currencyName: 'West African CFA Franc', symbol: 'Fr',  locale: 'fr-ML' },
  { code: 'MT', name: 'Malta',                 currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'mt-MT' },
  { code: 'MR', name: 'Mauritania',            currency: 'MRU', currencyName: 'Mauritanian Ouguiya',    symbol: 'UM',  locale: 'ar-MR' },
  { code: 'MU', name: 'Mauritius',             currency: 'MUR', currencyName: 'Mauritian Rupee',        symbol: 'Rs',  locale: 'en-MU' },
  { code: 'MX', name: 'Mexico',                currency: 'MXN', currencyName: 'Mexican Peso',           symbol: '$',   locale: 'es-MX' },
  { code: 'MD', name: 'Moldova',               currency: 'MDL', currencyName: 'Moldovan Leu',           symbol: 'L',   locale: 'ro-MD' },
  { code: 'MC', name: 'Monaco',                currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'fr-MC' },
  { code: 'MN', name: 'Mongolia',              currency: 'MNT', currencyName: 'Mongolian Tögrög',       symbol: '₮',   locale: 'mn-MN' },
  { code: 'ME', name: 'Montenegro',            currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'sr-ME' },
  { code: 'MA', name: 'Morocco',               currency: 'MAD', currencyName: 'Moroccan Dirham',        symbol: 'MAD', locale: 'ar-MA' },
  { code: 'MZ', name: 'Mozambique',            currency: 'MZN', currencyName: 'Mozambican Metical',     symbol: 'MT',  locale: 'pt-MZ' },
  { code: 'MM', name: 'Myanmar',               currency: 'MMK', currencyName: 'Myanmar Kyat',           symbol: 'K',   locale: 'my-MM' },
  { code: 'NA', name: 'Namibia',               currency: 'NAD', currencyName: 'Namibian Dollar',        symbol: 'N$',  locale: 'en-NA' },
  { code: 'NP', name: 'Nepal',                 currency: 'NPR', currencyName: 'Nepalese Rupee',         symbol: 'Rs',  locale: 'ne-NP' },
  { code: 'NL', name: 'Netherlands',           currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'nl-NL' },
  { code: 'NZ', name: 'New Zealand',           currency: 'NZD', currencyName: 'New Zealand Dollar',     symbol: 'NZ$', locale: 'en-NZ' },
  { code: 'NI', name: 'Nicaragua',             currency: 'NIO', currencyName: 'Nicaraguan Córdoba',     symbol: 'C$',  locale: 'es-NI' },
  { code: 'NE', name: 'Niger',                 currency: 'XOF', currencyName: 'West African CFA Franc', symbol: 'Fr',  locale: 'fr-NE' },
  { code: 'NG', name: 'Nigeria',               currency: 'NGN', currencyName: 'Nigerian Naira',         symbol: '₦',   locale: 'en-NG' },
  { code: 'NO', name: 'Norway',                currency: 'NOK', currencyName: 'Norwegian Krone',        symbol: 'kr',  locale: 'no-NO' },
  { code: 'OM', name: 'Oman',                  currency: 'OMR', currencyName: 'Omani Rial',             symbol: 'R.O', locale: 'ar-OM' },
  { code: 'PK', name: 'Pakistan',              currency: 'PKR', currencyName: 'Pakistani Rupee',        symbol: 'Rs',  locale: 'ur-PK' },
  { code: 'PA', name: 'Panama',                currency: 'PAB', currencyName: 'Panamanian Balboa',      symbol: 'B/.' ,locale: 'es-PA' },
  { code: 'PG', name: 'Papua New Guinea',      currency: 'PGK', currencyName: 'Papua New Guinean Kina', symbol: 'K',  locale: 'en-PG' },
  { code: 'PY', name: 'Paraguay',              currency: 'PYG', currencyName: 'Paraguayan Guaraní',     symbol: '₲',   locale: 'es-PY' },
  { code: 'PE', name: 'Peru',                  currency: 'PEN', currencyName: 'Peruvian Sol',           symbol: 'S/.' ,locale: 'es-PE' },
  { code: 'PH', name: 'Philippines',           currency: 'PHP', currencyName: 'Philippine Peso',        symbol: '₱',   locale: 'en-PH' },
  { code: 'PL', name: 'Poland',                currency: 'PLN', currencyName: 'Polish Złoty',           symbol: 'zł',  locale: 'pl-PL' },
  { code: 'PT', name: 'Portugal',              currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'pt-PT' },
  { code: 'QA', name: 'Qatar',                 currency: 'QAR', currencyName: 'Qatari Riyal',           symbol: 'QR',  locale: 'ar-QA' },
  { code: 'RO', name: 'Romania',               currency: 'RON', currencyName: 'Romanian Leu',           symbol: 'lei', locale: 'ro-RO' },
  { code: 'RU', name: 'Russia',                currency: 'RUB', currencyName: 'Russian Ruble',          symbol: '₽',   locale: 'ru-RU' },
  { code: 'RW', name: 'Rwanda',                currency: 'RWF', currencyName: 'Rwandan Franc',          symbol: 'Fr',  locale: 'rw-RW' },
  { code: 'SA', name: 'Saudi Arabia',          currency: 'SAR', currencyName: 'Saudi Riyal',            symbol: 'SR',  locale: 'ar-SA' },
  { code: 'SN', name: 'Senegal',               currency: 'XOF', currencyName: 'West African CFA Franc', symbol: 'Fr',  locale: 'fr-SN' },
  { code: 'RS', name: 'Serbia',                currency: 'RSD', currencyName: 'Serbian Dinar',          symbol: 'din', locale: 'sr-RS' },
  { code: 'SL', name: 'Sierra Leone',          currency: 'SLL', currencyName: 'Sierra Leonean Leone',   symbol: 'Le',  locale: 'en-SL' },
  { code: 'SG', name: 'Singapore',             currency: 'SGD', currencyName: 'Singapore Dollar',       symbol: 'S$',  locale: 'en-SG' },
  { code: 'SK', name: 'Slovakia',              currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'sk-SK' },
  { code: 'SI', name: 'Slovenia',              currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'sl-SI' },
  { code: 'SO', name: 'Somalia',               currency: 'SOS', currencyName: 'Somali Shilling',        symbol: 'Sh',  locale: 'so-SO' },
  { code: 'ZA', name: 'South Africa',          currency: 'ZAR', currencyName: 'South African Rand',     symbol: 'R',   locale: 'en-ZA' },
  { code: 'SS', name: 'South Sudan',           currency: 'SSP', currencyName: 'South Sudanese Pound',   symbol: '£',   locale: 'en-SS' },
  { code: 'ES', name: 'Spain',                 currency: 'EUR', currencyName: 'Euro',                   symbol: '€',   locale: 'es-ES' },
  { code: 'LK', name: 'Sri Lanka',             currency: 'LKR', currencyName: 'Sri Lankan Rupee',       symbol: 'Rs',  locale: 'si-LK' },
  { code: 'SD', name: 'Sudan',                 currency: 'SDG', currencyName: 'Sudanese Pound',         symbol: 'ج.س',locale: 'ar-SD' },
  { code: 'SE', name: 'Sweden',                currency: 'SEK', currencyName: 'Swedish Krona',          symbol: 'kr',  locale: 'sv-SE' },
  { code: 'CH', name: 'Switzerland',           currency: 'CHF', currencyName: 'Swiss Franc',            symbol: 'Fr',  locale: 'de-CH' },
  { code: 'SY', name: 'Syria',                 currency: 'SYP', currencyName: 'Syrian Pound',           symbol: '£',   locale: 'ar-SY' },
  { code: 'TW', name: 'Taiwan',                currency: 'TWD', currencyName: 'New Taiwan Dollar',      symbol: 'NT$', locale: 'zh-TW' },
  { code: 'TJ', name: 'Tajikistan',            currency: 'TJS', currencyName: 'Tajikistani Somoni',     symbol: 'SM',  locale: 'tg-TJ' },
  { code: 'TZ', name: 'Tanzania',              currency: 'TZS', currencyName: 'Tanzanian Shilling',     symbol: 'Sh',  locale: 'sw-TZ' },
  { code: 'TH', name: 'Thailand',              currency: 'THB', currencyName: 'Thai Baht',              symbol: '฿',   locale: 'th-TH' },
  { code: 'TL', name: 'Timor-Leste',           currency: 'USD', currencyName: 'US Dollar',              symbol: '$',   locale: 'pt-TL' },
  { code: 'TG', name: 'Togo',                  currency: 'XOF', currencyName: 'West African CFA Franc', symbol: 'Fr',  locale: 'fr-TG' },
  { code: 'TT', name: 'Trinidad and Tobago',   currency: 'TTD', currencyName: 'Trinidad Dollar',        symbol: 'TT$', locale: 'en-TT' },
  { code: 'TN', name: 'Tunisia',               currency: 'TND', currencyName: 'Tunisian Dinar',         symbol: 'DT',  locale: 'ar-TN' },
  { code: 'TR', name: 'Turkey',                currency: 'TRY', currencyName: 'Turkish Lira',           symbol: '₺',   locale: 'tr-TR' },
  { code: 'TM', name: 'Turkmenistan',          currency: 'TMT', currencyName: 'Turkmenistani Manat',    symbol: 'T',   locale: 'tk-TM' },
  { code: 'UG', name: 'Uganda',                currency: 'UGX', currencyName: 'Ugandan Shilling',       symbol: 'Sh',  locale: 'en-UG' },
  { code: 'UA', name: 'Ukraine',               currency: 'UAH', currencyName: 'Ukrainian Hryvnia',      symbol: '₴',   locale: 'uk-UA' },
  { code: 'AE', name: 'United Arab Emirates',  currency: 'AED', currencyName: 'UAE Dirham',             symbol: 'AED', locale: 'ar-AE' },
  { code: 'GB', name: 'United Kingdom',        currency: 'GBP', currencyName: 'British Pound',          symbol: '£',   locale: 'en-GB' },
  { code: 'US', name: 'United States',         currency: 'USD', currencyName: 'US Dollar',              symbol: '$',   locale: 'en-US' },
  { code: 'UY', name: 'Uruguay',               currency: 'UYU', currencyName: 'Uruguayan Peso',         symbol: '$U',  locale: 'es-UY' },
  { code: 'UZ', name: 'Uzbekistan',            currency: 'UZS', currencyName: 'Uzbekistani Som',        symbol: 'сум', locale: 'uz-UZ' },
  { code: 'VE', name: 'Venezuela',             currency: 'VES', currencyName: 'Venezuelan Bolívar',     symbol: 'Bs.S',locale: 'es-VE' },
  { code: 'VN', name: 'Vietnam',               currency: 'VND', currencyName: 'Vietnamese Đồng',        symbol: '₫',   locale: 'vi-VN' },
  { code: 'YE', name: 'Yemen',                 currency: 'YER', currencyName: 'Yemeni Rial',            symbol: '﷼',   locale: 'ar-YE' },
  { code: 'ZM', name: 'Zambia',                currency: 'ZMW', currencyName: 'Zambian Kwacha',         symbol: 'ZK',  locale: 'en-ZM' },
  { code: 'ZW', name: 'Zimbabwe',              currency: 'ZWL', currencyName: 'Zimbabwean Dollar',      symbol: 'Z$',  locale: 'en-ZW' },
];

// Get flag emoji from country code
export function getFlag(countryCode) {
  if (!countryCode) return '🌍';
  return countryCode
    .toUpperCase()
    .split('')
    .map(c => String.fromCodePoint(c.charCodeAt(0) + 127397))
    .join('');
}

// Get country by code
export function getCountry(code) {
  return COUNTRIES.find(c => c.code === code) || null;
}

// Format currency using Intl API — works for any currency worldwide
export function formatCurrency(amount, currency = 'USD', locale = 'en-US') {
  if (amount === null || amount === undefined || isNaN(amount)) return '—';
  try {
    return new Intl.NumberFormat(locale, {
      style: 'currency',
      currency,
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  } catch {
    // Fallback if currency/locale not supported
    const country = COUNTRIES.find(c => c.currency === currency);
    return `${country?.symbol ?? ''}${Number(amount).toLocaleString()}`;
  }
}
